### PR TITLE
sidenav: responsiveness fixed

### PR DESCRIPTION
**Pull request by nirparai**
- sidenav menu overlapping to main content area fixed
- contents from main area overlapping to sidebar area fixed
-

### CODE REVIEW

**Comment by GiffenGood1** [comment]
The overlapping is fixed but now the sidebar cant be collapsed when i click the hamburger icon, also we dont want the actual sidebar to be responsive it should have a fixed width and then automatically collapse at a certain screen size.

**Comment by nirparai** [comment]
Noted,

**Comment by nirparai** [comment]
Hi @SirkisMatt 

with recent commit

- hamburger menu fixes
- breakpoint set at 768px
-

can you please review it let me know for the changes

**Comment by GiffenGood1** [comment]
Hey @nirparai the sidenav is still nesting inside a responsive column you need to make it a SET WIDTH, probably best if its not in a column at all. It should work similar to how the mini draw here works https://material-ui.com/components/drawers/. So if a user wants to open the nav regardless of the screensize it should still open. right now the column is becoming small and cutting it off.

**Comment by nirparai** [comment]
@GiffenGood1 Hey matthew, sure I will have a look at drawers

**Comment by MaxLynam** [comment]
Hey there @nirparai  .... this does not seem right (as per clubhouse comment).  
I think @GiffenGood1  referral to you of the DRAWER example code, is the closest easy reference for you.  
  
**Check this example @nirpa**   
**https://material-ui.com/components/drawers/#mini-variant-drawer**

**Comment by GiffenGood1** [comment]
hey @nirparai, I checked out your latest update and it looks like how we wanted it good job. I'll let @SirkisMatt check it out too before we merge it but I think you can move on to another task now.

**Comment by nirparai** [comment]
@GiffenGood1 Thanks. sounds great.

**Comment by MaxLynam** [comment]
@SirkisMatt  ... could you have a quick review of this and see if it is good to be merged ??

**Comment by SirkisMatt** [comment]
Looks great! Good job @nirparai

**Pull request merged**
