### PR TITLE
Beneficiary

### PR DESCRIPTION
**Pull request by Bdhawa123**
Modified Add BeneficiaryForm.js

### CODE REVIEW

**Comment by GiffenGood1** [comment]
looks great, can you just add the same logic to the ArrayFieldDemographic file, so that we have the same effect when editing a demographic.

**Comment by MaxLynam** [comment]
@Bdhawa123 and @GiffenGood1  .... should this pull-request go back to "DRAFT" awaiting the update requested?

**Comment by Bdhawa123** [comment]
I'm still working on this

**Comment by GiffenGood1** [comment]
great stuff @Bdhawa123 looks great. Going to merge this in.

**Review by GiffenGood1 — APPROVED** [review]
Good work

**Comment by MaxLynam** [comment]
Woohoo ... well done @Bdhawa123 🎉

**Pull request merged**
